### ISSUE TITLE
Map Issue

### ISSUE THREAD

**Issue by shkoo25** [elasticrash/Angular2.leaflet.component#100]
Any solutions to this error?

angular2.leaflet.components/marker/marker.ts (113,8): Property 'map' does not exist on type 'Observable<Response>'.)

**Comment by elasticrash** [comment]
That's usually and basically a configuration problem. The problem is that rxjs is not being read properly.  A lot of things might causing this, from a wrong version of rxjs to the wrong version of node and npm. I need more info if I am going to be of any help.

**Comment by elasticrash** [comment]
Due to lack of information this issue is now closed
