### ISSUE TITLE
Problem with angular 2 cli

### ISSUE THREAD

**Issue by abdullah-abunada** [elasticrash/Angular2.leaflet.component#77]
ERROR in ./~/angular2.leaflet.components/marker/marker.ts
Module build failed: Error: /node_modules/angular2.leaflet.components/marker/marker.ts (117,8): Property 'map' does not exist on type 'Observable<Response>'.)
    at _checkDiagnostics (D:\Linux servers\sandbox\ng-map\node_modules\@ngtools\webpack\src\loader.js:116:15)
    at \node_modules\@ngtools\webpack\src\loader.js:141:17
 @ ./~/angular2.leaflet.components/index.js 5:15-41
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/map/map.ts
Module not found: Error: Can't resolve 'map.html' in '\node_modules\angular2.leaflet.components\map'
 @ ./~/angular2.leaflet.components/map/map.ts 115:22-41
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/map/map.ts
Module not found: Error: Can't resolve 'map.css' in '\node_modules\angular2.leaflet.components\map'
 @ ./~/angular2.leaflet.components/map/map.ts 116:21-39
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/layer/layer.ts
Module not found: Error: Can't resolve 'layer.html' in '\node_modules\angular2.leaflet.components\layer'
 @ ./~/angular2.leaflet.components/layer/layer.ts 69:22-43
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/layer/layer.ts
Module not found: Error: Can't resolve 'layer.css' in \node_modules\angular2.leaflet.components\layer'
 @ ./~/angular2.leaflet.components/layer/layer.ts 70:21-41
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/imageoverlay/image-overlay.ts
Module not found: Error: Can't resolve 'image-overlay.html' in ' \node_modules\angular2.leaflet.components\imageoverlay'
 @ ./~/angular2.leaflet.components/imageoverlay/image-overlay.ts 61:22-51
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/imageoverlay/image-overlay.ts
Module not found: Error: Can't resolve 'image-overlay.css' in '\node_modules\angular2.leaflet.components\imageoverlay'
 @ ./~/angular2.leaflet.components/imageoverlay/image-overlay.ts 62:21-49
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/circle/circle.ts
Module not found: Error: Can't resolve 'circle.html' in '\node_modules\angular2.leaflet.components\circle'
 @ ./~/angular2.leaflet.components/circle/circle.ts 83:22-44
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/circle/circle.ts
Module not found: Error: Can't resolve 'circle.css' in '\node_modules\angular2.leaflet.components\circle'
 @ ./~/angular2.leaflet.components/circle/circle.ts 84:21-42
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/polygon/polygon.ts
Module not found: Error: Can't resolve 'polygon.html' in '\node_modules\angular2.leaflet.components\polygon'
 @ ./~/angular2.leaflet.components/polygon/polygon.ts 99:22-45
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/polygon/polygon.ts
Module not found: Error: Can't resolve 'polygon.css' in 'D:\Linux servers\sandbox\ng-map\node_modules\angular2.leaflet.components\polygon'
 @ ./~/angular2.leaflet.components/polygon/polygon.ts 100:21-43
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/polyline/polyline.ts
Module not found: Error: Can't resolve 'polyline.html' in '\node_modules\angular2.leaflet.components\polyline'
 @ ./~/angular2.leaflet.components/polyline/polyline.ts 101:22-46
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/polyline/polyline.ts
Module not found: Error: Can't resolve 'polyline.css' in ' node_modules\angular2.leaflet.components\polyline'
 @ ./~/angular2.leaflet.components/polyline/polyline.ts 102:21-44
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/geojson/geojson.ts
Module not found: Error: Can't resolve 'geojson.html' in '  node_modules\angular2.leaflet.components\geojson'
 @ ./~/angular2.leaflet.components/geojson/geojson.ts 63:22-45
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/geojson/geojson.ts
Module not found: Error: Can't resolve 'geojson.css' in ' node_modules\angular2.leaflet.components\geojson'
 @ ./~/angular2.leaflet.components/geojson/geojson.ts 64:21-43
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/popup/popup.ts
Module not found: Error: Can't resolve 'popup.html' in ' node_modules\angular2.leaflet.components\popup'
 @ ./~/angular2.leaflet.components/popup/popup.ts 62:22-43
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/popup/popup.ts
Module not found: Error: Can't resolve 'popup.css' in ' node_modules\angular2.leaflet.components\popup'
 @ ./~/angular2.leaflet.components/popup/popup.ts 63:21-41
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/group/group.ts
Module not found: Error: Can't resolve 'group.html' in ' node_modules\angular2.leaflet.components\group'
 @ ./~/angular2.leaflet.components/group/group.ts 35:22-43
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/angular2.leaflet.components/group/group.ts
Module not found: Error: Can't resolve 'group.css' in ' node_modules\angular2.leaflet.components\group'
 @ ./~/angular2.leaflet.components/group/group.ts 36:21-41
 @ ./~/angular2.leaflet.components/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

**Comment by elasticrash** [comment]
I don't fully support webpack at the time only SystemJs see issue #74 #75
