### ISSUE TITLE
Marker is slow

### ISSUE THREAD

**Issue by Bengreen** [elasticrash/Angular2.leaflet.component#89]

**Comment by elasticrash** [comment]
marker should only be slow when you use a custom marker icon which has a significant size. Normal markers should be fine. The only alternative for custom markers is making the user to set the value size as a @input value. I can make it so, if you provide a size, to not, try to figure the size by it self.

**Comment by Bengreen** [comment]
I was testing this for a dataset of 650 markers and the performance was very poor. (110secs)
I was using the standard leaflet marker (as a custom URL) so it was not a large image.
i also tried without specifying the custom icon url and using default, but for some reason it did not work correctly and resulted in an file load error (stange filename... I think this is an issue with leaflet). However the time was still 72 secs.

How many markers would be expected to use on a map ? I looked at some examples where it suggests that 1k is reasonable.

When i run the same example with 100 markers i get much more reasonable performance. (7 sec) with default options. and 3 secs with custom icon. (that surprised me....But may be something to do with the non-resolvable icon image is making the rendering slower).

Either way there is something strange happening as the number of markers grows.

**Comment by Bengreen** [comment]
with circle it is 26 secs for 650 data points. (again that is slow).
Any ideas on how to speed things up ?

**Comment by Bengreen** [comment]
For reference my code is as follows:
```
<leaf-element [lat]=54.607868 [lon]=-5.926437 [zoom]=13 [minZoom]=11 [maxZoom]=13 [layerControl]=true [zoomControl]="true" [maxBounds]="[[54.770692,-6.153943],[54.505049, -5.712621]]" class="col-xs-12 col-md-9" style="height: 600px;" >
		    <layer-element [slippyLayer]="'assets/map/20170112_osm/{z}/{x}/{y}.png'" [attribution]="'&copy; <a href=&quot;http://www.openstreetmap.org/copyright&quot;>OpenStreetMap</a>, Tiles courtesy of <a href=&quot;http://hot.openstreetmap.org/&quot; target=&quot;_blank&quot;>Humanitarian OpenStreetMap Team</a>'" [name]="'OSM Offline'"></layer-element>
            <leaflet-group [name]="'Cities'">
                <marker-element [lat]=54.596943 [lon]=-5.930074 [mouseover]="'Belfast'" [iconUrl]="cityMarker"></marker-element>
            </leaflet-group>

            <leaflet-group [name]="'Interests'">

                <circle-element *ngFor="let myMark of attractionsTop" [lat]=myMark.geo[0] [lon]=myMark.geo[1] [mouseover]=myMark.name ></circle-element>
            </leaflet-group>


        </leaf-element>
```

**Comment by elasticrash** [comment]
I'll write a test that generates random points (already have one for different reasons) and I'll see how it behaves and where it starts to break, so far the only example/test I got with points is the star map  https://elasticrash.github.io/Angular.io.MapViewer/example/#/simple with 210 points (which loads in less than 4 seconds)

**Comment by elasticrash** [comment]
I tried the following example 
https://elasticrash.github.io/Angular.io.MapViewer/example/#/random
with 
600 circles (which also creates 600 a line with 600 nodes every few seconds) and took ~14sec to load

the same example with markers took ~75secs to load properly. I say properly because the map with the un-rendered points take less than ~2 secs.

I am running a more substantial test atm and Ill let you know about the results

**Comment by elasticrash** [comment]
there is indeed something weird when it comes to execution time of marker.ts but at the moment I don't know who is causing the delays, me or leaflet (or angular?)

![loadtimes](https://cloud.githubusercontent.com/assets/5920069/21959519/5c1ae7ae-dac1-11e6-9869-6f963a021307.png)

the y-axis is ms

**Comment by Bengreen** [comment]
OK. So if i was seeing 2sec max and 0.25 sec as normal that would be ok by me. But i am seeing circa 120 secs.
Can you send the link to your source code for the test ... maybe i am doing something silly.

**Comment by Bengreen** [comment]
I have been drilling into the code specifically the group.ts and found some oddities that i think explain the performance.
The groupLayer was being removed, constructed and re-attached every time a new marker or element was being added.
I have taken a stab and creating a new version that uses addLayer instead and it is much faster.

**Comment by elasticrash** [comment]
But there is really a valid reason for doing that though, its because leaflet doesn't preserve the order layer. The group is mainly useful when you have a layer control. Turning on and off all of them. Maybe I can work around the concept that if an element is of the same type (*ngFor) not to add the group until all points are loaded. I'll give it a go.

**Comment by elasticrash** [comment]
Yeah Ill use AddLayer seems much safer. Thanks :smile:

**Comment by elasticrash** [comment]
Now it works fine for up to 1000 markers...after that point markers still load really fast, but at least in my browser, the map is barely responsive. Ill run the tests on the evening and if everything seem fine, I'll schedule the change for release.

**Comment by Bengreen** [comment]
i marker.ts down to a much smaller definition.

```
    ngOnInit() {
        if (this.LeafletElement || this.LeafletGroup) {

            let map = this.mapService.getMap();

            //trick to match the number of layers
            if (this.LeafletGroup) {
                this.groupService.increaseNumber();
            }

            var marker = L.marker([this.lat, this.lon], {
                title: this.title,
                icon: this.icon,
            });
            if (this.popup) {
                marker.bindPopup(this.popup, {
                    offset: L.point(12, 6)
                }).openPopup();
            }

            this.createMarkerlayer(marker, map);

        }
    }
```
... I was trying out some stuff to minimise the code and match the code as close as possible to Leaflet's APIs and levels of abstraction to allow code  and know how to be easily mapped over.

What are your thoughts on this? Will try to get some progress then share as an comparison.

**Comment by elasticrash** [comment]
my main concern about the marker is that I don't want to guess that I know the marker size beforehand. So basically if you don't care about custom icons ...you can make the marker.ts just 8 lines long. I guess just make the user input the width and height of the icon... but I felt it would eventually be really annoying to someone that uses many icons of various sizes.  And depending on the icon dimensions you need then too figure out anchor locations and such. 

http://leafletjs.com/reference.html#icon

**Comment by Bengreen** [comment]
yes. I see that there can be lots of stuff to set.
On the other hand it creates a library that is closely linked to Leaflet but different which will be confusing.
I was looking and it might be able to solve this in two directions. To place the functionality you are suggesting into a helper function (which can make some good assumptions with respect to your marker) e.g. the point is at the bottom and middle (although this definitely needs an ability to override or it becomes a limitation).
Then to also use that helper function to set the default icon for `new L.Icon.Default()`
