### ISSUE TITLE
Marker.ts webpack build error: Property 'map' does not exist

### ISSUE THREAD

**Issue by hotshotguy** [elasticrash/Angular2.leaflet.component#92]
I've added your components (v1.2.6) to [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter), created my own component where I fetch data from server with Http. On build error occurs:
`[at-loader] Checking finished with 1 errors`
`[at-loader] node_modules/angular2.leaflet.components/marker/marker.ts:114:8`
    `Property 'map' does not exist on type 'Observable<Response>'. `
I've removed ./node_modules/angular2.leaflet.components/node_modules/rxjs, and added in my bootstrap file:
`import 'rxjs/Rx';`
and build succeeded.

**Comment by EvgenyKravchenko** [comment]
Rxjs versions are equal.., why is this happening? Is there some good way to fix this, so we don't need to remove node_modules manually? 
Is this fix going to be integrated in the package?

**Comment by elasticrash** [comment]
I didn't give it a though when I saw this issue, because I was too busy lately (translation I have a small kid demanding time non stop <3)....but why would even node_modules exist inside the npm module? I haven't seen nested dependencies in npm since the middle ages
