### ISSUE TITLE
Missing map import?

### ISSUE THREAD

**Issue by mariuspruski** [elasticrash/Angular2.leaflet.component#95]
I followed the instructions to install+use your leaflet components and got the folllowing error:

`ERROR in ./~/angular2.leaflet.components/marker/marker.ts`
`Module build failed: Error: D:/Projects/ngx/node_modules/angular2.leaflet.components/marker/marker.ts (114,8): Property 'map' does not exist on type 'Observable<Response>'.)`

Apparently there's something wrong with the dependencies, maybe that's on my end? npm doesn't show any missing dependencies though. I have the following versions:
npm: '3.10.9',
node: '6.9.2',
rxjs: '5.0.3',
angular2.leaflet.components: '1.2.6'

**Comment by elasticrash** [comment]
Do you use typings in your project? Ive seen this error when you use es6 typings. My library uses @types since 1.2.4

**Comment by mariuspruski** [comment]
I'm also just using @types in my project. Sorry I can't provide more information, I'm relatively new to all this.

**Comment by elasticrash** [comment]
I have a demo project located here: https://github.com/elasticrash/Angular.io.MapViewer/tree/developing_npm_module
using systemJS. Maybe this will help.

if you are using webpack, I include a webpack config in the repo.

**Comment by mariuspruski** [comment]
I couldn't get that project to run, either. I'll leave it at that, sorry for the trouble.

**Comment by elasticrash** [comment]
I am doing all the development on that project and I've tried it in a lot of computers. Maybe you should update your npm  is slightly old (october 16) and a major version down
