### ISSUE TITLE
marker and popup error.

### ISSUE THREAD

**Issue by bonaparte89** [elasticrash/Angular2.leaflet.component#98]
hello,
i have some build issues. We / I'm using systemjs.
the second error was actually mentioned #74 here already.

`node_modules/angular2.leaflet.components/marker/marker.ts(65,65): error TS2345: Argument of type '{ icon: Icon; }' is not assignable to parameter of type 'MarkerOptions'.
  Property 'options' is missing in type '{ icon: Icon; }'.
node_modules/angular2.leaflet.components/marker/marker.ts(113,12): error TS2322: Type 'Observable<any>' is not assignable to type 'Observable<any>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
node_modules/angular2.leaflet.components/popup/popup.ts(33,109): error TS2345: Argument of type 'string' is not assignable to parameter of type '(source: Layer) => string | HTMLElement'.`

I changed some lines on those two files to make it work. 
I will create a pull request for those issues

**Comment by elasticrash** [comment]
That's absolutely fine, but can you please let me know which version of typescript you are using? cause in version 2.1.4 and 2.1.5 I am not getting any errors what's so ever.

**Comment by bonaparte89** [comment]
using 2.1.5

**Comment by elasticrash** [comment]
I merged it into develop, I am going to run a few tests before releasing it, as always =D
